CROSS_COMPILE ?= mips-linux-gnu-


ifeq (${ISVP_ENV_KERNEL_DIR}, )
	ISVP_ENV_KERNEL_DIR = $(PWD)/../../kernel
endif
ISVP_ENV_KERNEL_DIR = /home_a/ppchen/isvp/ISVP-T31-1.1.0-20200115/software/sdk/Ingenic-SDK-T31-1.1.0-20200115/opensource/kernel
KDIR = /home_a/ppchen/isvp/ISVP-T31-1.1.1-20200508/software/sdk/Ingenic-SDK-T31-1.1.1-20200508/opensource/kernel

KDIR := ${ISVP_ENV_KERNEL_DIR}
MODULE_NAME := libuac
# MODULE_NAME := g_audio


$(MODULE_NAME)-objs := f_uac1.o utils/node_list.o

obj-m += $(MODULE_NAME).o

all: modules

modules:
	@$(MAKE) -C $(KDIR) M=$(shell pwd) $@

cpy:
	cp $(MODULE_NAME).o ../ucamera_driver/libuac.a

clean:
	find . -name "*.o" | xargs rm -vf
	find . -name ".cmd" | xargs rm -vf
	find . -name "\.*cmd" | xargs rm -vf
	@rm -rf *.o *~ .depend .*.cmd  *.mod.c .tmp_versions *.ko *.symvers modules.order
